version: '3'
services:

  mongo:
    image: mongo:4.4.10
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=eda
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: [ "--replSet", "rs0", "--bind_ip_all" ]

  mongo-express:
    image: library/mongo-express:latest
    container_name: mongo-express
    ports:
      - "9090:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: unless-stopped
    
  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0           # Disable running-tests so the cluster starts faster
    ports:
      - 2181:2181           # Zookeeper
      - 3030:3030           # Landoop UI
      - 8081-8083:8081-8083 # REST Proxy, Schema Registry and Kafka Connect
      - 9581-9585:9581-9585 # JMX Ports
      - 9092:9092           # Kafka Broker 
    volumes:
      - ./kafka-connect/connectors/mongo-kafka-connect-1.7.0-confluent.jar:/connectors/mongo-kafka-connect-1.7.0-confluent.jar
