spring:  
  data:
    mongodb:
      database: videoclub
      auto-index-creation: true
booking-sv:
  groupId: booking-sv
  topic:
    consume:
      movieReserved: videoclub-movie-reserved
      movieRejected: videoclub-movie-rejected
      userInvalidated: videoclub-user-invalidated