spring:  
  data:
    mongodb:
      database: videoclub
      auto-index-creation: true

user-sv:
  groupId: user-sv
  topic:
    consume:
      bookingCreated: videoclub-bookings-created
    produces:
      userValidated: videoclub-user-validated